#:schema node_modules/wrangler/config-schema.json
name = "frontend"
compatibility_date = "2026-04-03"

[build]
command = "cd frontend && yarn install && yarn build"

[assets]
directory = "./frontend/dist"
